<style>
    .post { margin: 5px 0 0 5px; border: 1px solid grey; width: 450px; min-height: 100px;}
    .author { margin-left: 10px; }
    .text { padding-left: 15px; padding-top: 15px; }
    .date {color: grey; font-size: 11px;}
    .admin a { color: #46468b; float: right; padding-right: 15px; }
</style>

Список сообщений: <br>

<?php
/** @var $post \App\Models\Post */
/** @var $user \App\Models\User */
$user = $this->user;
?>
<?php if($posts = $this->posts): ?>
    <?php foreach ($posts as $post): ?>
        <div class="post">
            <? if($user->isAdmin()): ?>
                <div class="admin">
                    <a href="/admin/deletePost/?id=<?=$post->getId();?>">Удалить пост</a>
                </div>
            <? endif; ?>
            <span class="date"><?=$post->getCreatedAt();?> </span>
            <? if($author = $post->getAuthor()):?>
                <span class="author"><?=htmlspecialchars($author->getName());?></span>
            <? else: ?>
                <span class="author">Автор был удален за ненадобностью</span>
            <? endif; ?>
            <div class="text"><?=htmlspecialchars(nl2br($post->getText()));?></div>
            <? if($post->getImage()):?>
                <div><img src="/images/<?=$post->getImage();?>" style="width: 150px;"></div>
            <? endif;?>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    Постов пока нет
<?php endif; ?>

Добавить пост
<form enctype="multipart/form-data" action="/blog/createPost" method="post">
    <textarea style="width: 250px; height: 150px;" type="text" value="" name="text"></textarea><br><br>
    Изображение: <input type="file" name="image"><br>
    <input type="submit" value="Отправить">
</form>